backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

i18n:
  structure: single_file
  locales: [pl, en, cs]
  default_locale: pl

collections:
  - name: "pages"
    label: "Pages"
    i18n:
      structure: single_file
      locales: [pl, en, cs]
      default_locale: pl
    files:
      - name: "index"
        label: "Landing Page"
        file: "src/pages/index.md"
        i18n: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Home Title, name: homeTitle, widget: string, i18n: true}
          - {label: Home Description, name: homeDescription, widget: text, i18n: true}
          - {label: Home Background, name: homeBackground, widget: image, required: false, i18n: false}
          - {label: Home Font Color, name: homeFontColor, widget: color, required: false, i18n: false}
          - {label: About Title, name: aboutTitle, widget: string, i18n: true}
          - {label: About Description, name: aboutDescription, widget: text, i18n: true}
          - {label: About Background, name: aboutBackground, widget: image, required: false, i18n: false}
          - {label: About Font Color, name: aboutFontColor, widget: color, required: false, i18n: false}
          - {label: Demo Title, name: demoTitle, widget: string, i18n: true}
          - {label: Demo Description, name: demoDescription, widget: text, i18n: true}
          - {label: Demo Background, name: demoBackground, widget: image, required: false, i18n: false}
          - {label: Demo Font Color, name: demoFontColor, widget: color, required: false, i18n: false}
          - {label: Demo Video Url, name: demoVideoUrl, widget: string, required: false, i18n: true}
          - {label: Release Date, name: releaseDate, widget: datetime, required: false, i18n: duplicate}
